services:
  therapist-backend:
    image: therapist-backend:0.0.1
    build:
      context: backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://therapist-ai:11434
      - OLLAMA_MODEL=llama3.1
    depends_on:
      - therapist-ai

  therapist-frontend:
    image: therapist-frontend:0.0.1
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - therapist-backend

  therapist-ai:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve & ollama pull llama3.1 && ollama run llama3.1 && tail -f /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    restart: unless-stopped

volumes:
  ollama:
